name: MDBuildOff
version: '${project.version}'
main: org.naosh.mdbuildoff.MDBuildOff
api-version: '1.20'
depend: [MDTeams]
softdepend: [MDTeams]
commands:
  buildoff:
    description: buildoff master command
    usage: /<command>
    permission: buildoff