name: DecathlonManager
version: '${project.version}'
main: decathlonmanager.decathlonmanager.DecathlonManager
api-version: 1.20
depend: [MDTeams, TnTRun, BuildOff, MDUHC]
softdepend: [MDTeams, TNTRun, BuildOff, MDUHC]
commands:
  manager:
    description: manages the Decathlon
    usage: /<command>
    permission: manager
