name: DecathlonManager
version: '${project.version}'
main: org.naosh.decathlonmanager.DecathlonManager
api-version: '1.20'
depend: [MDTeams, MDBuildOff]
softdepend: [MDTeams, MDBuildOff]
commands:
  manager:
    description: manages the Decathlon
    usage: /<command>
    permission: manager